### ISSUE TITLE
Problems with V1-beta of Quasar framework

### ISSUE THREAD

**Issue by mfreeman451** [wmfs/quasar-map-mapbox#3]
Getting errors with latest version of Quasar framework and your component:

vue.runtime.esm.js:619 [Vue warn]: Error in data(): "TypeError: Cannot read property 'expression' of undefined"

found in

---> <QMap> at node_modules/@wmfs/quasar-map-mapbox/lib/QMap.vue

It appears here:

  data () {
    const templCentre = [this.centreLongitude, this.centreLatitude]
    const model = this.$vnode.data.model

I believe this.$vnode.data.model does not exist, it is coming back as model undefined for me.

**Comment by reecebrend** [comment]
Hi @mfreeman451 sorry for the delay in getting back to you.

Can you confirm if you are still having this issue, and if so can you confirm what version of Quasar you're currently running? 

Thanks

**Comment by mfreeman451** [comment]
I've moved on, it was the latest version at the time.

**Comment by reecebrend** [comment]
Okay no problem. 

I'm going to close this issue since your problem is now resolved.

**Comment by mfreeman451** [comment]
Its not resolved, the quasar mapbox implementation is broken..
